name: 'Performance & Accessibility CI'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    perf-access:
        name: Lighthouse & Accessibility Audit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Audit dependencies
              run: npm audit --audit-level=high

            - name: Wait for Vercel to finish deployment
              run: sleep 60

            - name: Get Vercel Preview URL
              id: vercel_preview_url
              uses: zentered/vercel-preview-url@v1.4.0
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              with:
                  vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

            - name: Confirm Preview URL
              run: echo "Preview deployed at https://${{ steps.vercel_preview_url.outputs.preview_url }}"

            - name: Run Lighthouse CI
              uses: treosh/lighthouse-ci-action@v12
              env:
                  VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
              with:
                  urls: https://${{ steps.vercel_preview_url.outputs.preview_url }}
                  configPath: .lighthouserc.js

            - name: Run Pa11y CI
              env:
                  VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
              run: npx pa11y-ci --config .pa11yci.js https://${{ steps.vercel_preview_url.outputs.preview_url }}
