name: 'Performance & Accessibility CI'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    perf-access:
        name: Lighthouse & Accessibility Audit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Audit dependencies
              run: npm audit --audit-level=high

            - name: Build production
              run: npm run build

            - name: Serve production
              run: npm run start &

            - name: Wait for server to start
              run: npx wait-on http://localhost:3000

            - name: Run Lighthouse CI
              uses: treosh/lighthouse-ci-action@v8
              with:
                  urls: http://localhost:3000
                  configPath: .lighthouserc.js

            - name: Run A11yWatch accessibility audit
              uses: a11ywatch/github-action@v2.1.10
              with:
                  WEBSITE_URL: 'http://localhost:3000'
                  SITE_WIDE: true
